
# Jupyter Book configuration
# Docs: https://jupyterbook.org/en/stable/customize/config.html
title: "Research Coding Community" # <-- change this
author: "Your Community or Organization" # <-- and this!
logo: "_static/logo.png" 
copyright: "2025"

only_build_toc_files: true

repository:
  url: https://github.com/coding-for-reproducible-research/RCC_Coding_Club_Template  # <-- and this!
  branch: main
  path_to_book: ""

html:
  favicon: "_static/logo.png"
  use_repository_button: true
  use_edit_page_button: true
  use_issues_button: true

launch_buttons:
  binderhub_url: "https://mybinder.org"
  colab_url: ""

sphinx:
  extra_extensions:
    - sphinx_togglebutton

execute:
  execute_notebooks: auto
